# Generated by Django 4.0.1 on 2022-01-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_departamento_funcionario_empresa_and_more'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(help_text='Escreva o motivo da hora extra...', max_length=100),
        ),
    ]
